import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const SHARED_KEYS = new Set([
  "BUTTON$REFRESH",
  "WORKSPACE$TITLE",
  "COMMON$CLEAR_SELECTION",
  "BUTTON$SEND",
  "CONVERSATION$READY",
  "COMMON$WORKING",
  "COMMON$PAUSED",
  "COMMON$ERROR",
]);
const keepKey = (key) => key.startsWith("INSIDER_CAT$") || SHARED_KEYS.has(key);

export async function buildBundle() {
  const source = readFileSync(
    new URL("src/extension.js", import.meta.url),
    "utf8",
  );
  const skill = readFileSync(
    new URL("skills/insider-cat/SKILL.md", import.meta.url),
    "utf8",
  )
    .replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, "")
    .trim();
  if (!source.includes('"__INSIDER_SKILL_TEXT__"'))
    throw new Error("Missing skill placeholder");
  const definitions = JSON.parse(
    readFileSync(new URL("src/i18n/translation.json", import.meta.url), "utf8"),
  );
  const subset = Object.fromEntries(
    Object.entries(definitions).filter(([key]) => keepKey(key)),
  );
  const result = await build({
    stdin: {
      contents: source.replace('"__INSIDER_SKILL_TEXT__"', () =>
        JSON.stringify(skill),
      ),
      resolveDir: fileURLToPath(new URL("src", import.meta.url)),
      sourcefile: "extension.js",
      loader: "js",
    },
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    write: false,
    minify: true,
    define: { "process.env.NODE_ENV": '"production"' },
    legalComments: "inline",
    banner: {
      js: "// Generated by build.mjs. Edit src/extension.js.",
    },
    plugins: [
      {
        name: "insider-localization-subset",
        setup(plugin) {
          plugin.onLoad(
            { filter: /[\\/]src[\\/]i18n[\\/]translation\.json$/ },
            () => ({ contents: JSON.stringify(subset), loader: "json" }),
          );
          plugin.onLoad(
            { filter: /[\\/]src[\\/]i18n[\\/]declaration\.js$/ },
            () => ({
              contents: `export const I18nKey = ${JSON.stringify(Object.fromEntries(Object.keys(subset).map((key) => [key, key])))};`,
              loader: "js",
            }),
          );
        },
      },
    ],
  });
  return result.outputFiles[0].text;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(new URL("extension.js", import.meta.url), await buildBundle());
}
